# Network Parameters
network_rules: Deny
paas_public: false
dns: ["10.30.0.197","10.30.0.229"]
azfw_zones: [1,2,3]


# Hub VNET
hub_cidr: "10.30.0.0/22"
gateway_cidr: "10.30.0.0/26"
azfw_cidr: "10.30.0.64/26"
bastion_cidr: "10.30.0.128/26"
dns01_cidr: "10.30.0.192/27"
dns02_cidr: "10.30.0.224/27"
dns03_cidr: "10.30.1.0/27"
dns04_cidr: "10.30.1.32/27"

# Management VNET
mgmt_cidr: "10.30.4.0/22"
devops_cidr: "10.30.4.64/26"
pe_cidr: "10.30.4.0/26"
shared_cidr: "10.30.4.128/26"


# On-Prem Network Address Spaces
onprem01: "10.0.0.0/8"
onprem02: "172.16.0.0/12"
vpn_prefix: "10.200.1.0/24"
vpn_pip1: "1.2.3.4"

# VM Parameters
vm_count: 2
devops_vm_count: 1
vm_size1: "Standard_B2ms"
vm_size2: "Standard_DS2_v2"

# Governance Parameters
enforce_policy: false
costcenter_tag: 7941
owner_tag: "Owner"
team_tag: Azure_Architects